server:
  port: 8081

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa

  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:sql/schema-init.sql

